// Copy is scoped to the v2 integration. Translation of these screens is a later stage.
export const V2_COPY: Record<string, string> = {
 "v2.tabs.journey": "Mi recorrido", "v2.tabs.aria": "Mi piloto",
 "v2.country.search": "Buscar país", "v2.country.none": "Sin resultados",
 "v2.streak.aria": "Racha de {{count}} días", "v2.profile.back_aria": "Volver a mi perfil",
 "v2.common.play_now": "Jugar", "v2.common.sending": "Enviando…",
 "v2.common.yes_remove": "Eliminar", "v2.common.err_network": "No pudimos conectar. Inténtalo de nuevo.",
 "v2.common.err_generic": "No pudimos completar la acción.",
 "v2.common.err_rate": "Espera un momento y vuelve a intentarlo.",
 "v2.identity.name_label": "Nombre de piloto", "v2.identity.detecting": "Detectando país…",
 "v2.identity.err_country": "Selecciona un país válido.", "v2.identity.err_name": "Escribe un nombre de 1 a 30 caracteres.",
 "v2.identity.err_name_month": "Podrás cambiar tu nombre el próximo mes.",
 "v2.identity.err_unauthorized": "Vuelve a iniciar sesión para continuar.",
 "v2.badges.err_stale": "Actualiza tu colección y vuelve a intentarlo.", "v2.badges.choose": "Elegir insignias",
 "v2.access.eyebrow": "Tu lugar en la grilla", "v2.access.title_1": "Un nombre.",
 "v2.access.title_2": "Tu historia", "v2.access.gate_note": "Confirma tu piloto para jugar.",
 "v2.access.card_label": "Tu piloto", "v2.access.card_hint": "Así apareces en la clasificación",
 "v2.access.benefit_sync_title": "Tu progreso, contigo.", "v2.access.benefit_sync_body": "En todos tus dispositivos.",
 "v2.access.benefit_own_title": "Una identidad propia.", "v2.access.benefit_own_body": "Nombre, país e insignias.",
 "v2.access.benefit_share_title": "Mejor en compañía.", "v2.access.benefit_share_body": "Amigos y retos compartidos.",
 "v2.access.welcome": "Bienvenido a Box Daily Box", "v2.access.logged_title": "Ya estás dentro.",
 "v2.access.logged_body": "{{email}}", "v2.access.go_profile": "Ir a mi piloto",
 "v2.access.card_title": "Entra a tu cuenta", "v2.access.card_body": "Guarda tu progreso y juega desde cualquier dispositivo.",
 "v2.access.google": "Continuar con Google", "v2.access.divider": "o",
 "v2.access.guest_title": "Empieza a tu ritmo", "v2.access.guest_body": "Sin crear una cuenta.",
 "v2.access.save_continue": "Guardar y continuar", "v2.access.guest_button": "Seguir como visitante",
 "v2.access.guest_hint": "Confirmas el nombre y país de tu tarjeta.",
 "v2.access.legal": "Al continuar, aceptas los", "v2.access.terms": "Términos y condiciones", "v2.access.privacy": "Privacidad",
 "v2.friends.eyebrow": "Tu equipo fuera de pista", "v2.friends.subtitle": "La próxima vuelta, juntos.",
 "v2.friends.locked_title": "Tu grilla empieza aquí", "v2.friends.anon_cta": "Conectar con Google",
 "v2.friends.connect_eyebrow": "Un código. Más compañía.", "v2.friends.connect_title": "Amplía tu grilla",
 "v2.friends.connect_body": "Comparte tu código o añade el de un amigo.", "v2.friends.your_code": "Tu código",
 "v2.friends.copy_code": "Copiar", "v2.friends.friend_code": "Código de tu amigo", "v2.friends.add": "Añadir",
 "v2.friends.requests_title": "Solicitudes", "v2.friends.request_one": "1 pendiente",
 "v2.friends.request_other": "{{count}} pendientes", "v2.friends.wants_to_join": "Quiere unirse a tu grilla",
 "v2.friends.list_title": "Tu grilla", "v2.friends.online_count": "{{count}} en línea",
 "v2.friends.challenge": "Retar", "v2.friends.remove": "Eliminar",
 "v2.friends.err_self": "Ese es tu código.", "v2.friends.err_code_not_found": "No encontramos ese código.",
 "v2.friends.err_user_not_found": "No encontramos a ese piloto.",
 "v2.friends.err_already_friends": "Ya está en tu grilla.",
 "v2.friends.err_already_sent": "Ya enviaste una solicitud.",
 "v2.friends.err_request_gone": "Esta solicitud ya no está disponible.",
 "v2.ach.eyebrow": "Cada vuelta deja huella", "v2.ach.title": "Logros", "v2.ach.subtitle": "Pequeñas metas. Grandes historias.",
 "v2.ach.empty_title": "Tu colección empieza jugando", "v2.ach.empty_body": "Completa un reto para empezar.",
 "v2.ach.unlocked_label": "Logros desbloqueados", "v2.ach.earned_label": "Todas tus insignias de logros",
 "v2.ach.none_yet": "Tu primera insignia te espera", "v2.ach.next_eyebrow": "Tu próxima meta", "v2.ach.to_go": "para lograrlo",
 "v2.ach.all_eyebrow": "Colección completa", "v2.ach.all_title": "Todas las metas, cumplidas.",
 "v2.ach.all_body": "Sigue sumando vueltas.", "v2.ach.collection": "Tu colección",
 "v2.ach.footnote": "Elige en tu perfil cuáles mostrar en el ranking.",
 "v2.ach.completed": "Meta cumplida", "v2.ach.not_started": "Por empezar", "v2.ach.complete_short": "Completo",
 "v2.ach.unlocked_on": "Desbloqueado el {{date}}", "v2.ach.best_day": "Mejor día: {{current}} de {{target}}",
 "v2.ach.perfect_day_pending": "Gana todos los retos en un día.",
 "v2.ach.progress_games": "{{current}} / {{target}} juegos", "v2.ach.progress_wins": "{{current}} / {{target}} victorias",
 "v2.ach.goal_perfect_day": "Gana los {{target}} retos en una misma jornada.",
 "v2.ach.goal_legend_one": "Una victoria en Leyenda y es tuyo.", "v2.ach.goal_legend_other": "{{count}} victorias en Leyenda y es tuyo.",
 "v2.ach.goal_specialist_one": "Una victoria más en {{game}}.", "v2.ach.goal_specialist_other": "{{count}} victorias más en {{game}}.",
 "v2.ach.goal_specialist_any_one": "Una victoria más en un mismo juego.", "v2.ach.goal_specialist_any_other": "{{count}} victorias más en un mismo juego.",
 "v2.ach.goal_complete_one": "Gana un juego más de la colección.", "v2.ach.goal_complete_other": "Gana {{count}} juegos más de la colección.",
 "v2.ach.goal_wins_one": "Una victoria más y es tuyo.", "v2.ach.goal_wins_other": "{{count}} victorias más y es tuyo.",
 "v2.ach.left_games_one": "Falta 1 juego", "v2.ach.left_games_other": "Faltan {{count}} juegos",
 "v2.ach.left_wins_one": "Falta 1 victoria", "v2.ach.left_wins_other": "Faltan {{count}} victorias",
 "v2.ach.specialist_left_one": "1 victoria más en {{game}}", "v2.ach.specialist_left_other": "{{count}} victorias más en {{game}}",
 "badge.annual_gold": "Campeón anual", "badge.annual_silver": "Subcampeón anual", "badge.annual_bronze": "Tercer puesto anual",
 "badge.tooltip_annual_gold_one": "Campeón de {{month}}", "badge.tooltip_annual_gold_many": "Campeón de {{months}}",
 "badge.tooltip_annual_silver_one": "Segundo puesto en {{month}}", "badge.tooltip_annual_silver_many": "Segundo puesto en {{months}}",
 "badge.tooltip_annual_bronze_one": "Tercer puesto en {{month}}", "badge.tooltip_annual_bronze_many": "Tercer puesto en {{months}}",
 "seo.account.ranking.title": "Clasificación | Box Daily Box", "seo.account.access.title": "Inicio de sesión | Box Daily Box",
 "seo.account.profile.title": "Mi piloto | Box Daily Box", "seo.account.achievements.title": "Logros | Box Daily Box",
 "seo.account.friends.title": "Amigos | Box Daily Box", "seo.account.description": "Tu recorrido en Box Daily Box."
};

export function v2Copy(key: string, vars?: Record<string, string | number>): string | null {
 const value = V2_COPY[key];
 if (value === undefined) return null;
 return value.replace(/\{\{(\w+)\}\}/g, (match, name: string) => vars?.[name] === undefined ? match : String(vars[name]));
}
